### ISSUE TITLE
Vim(ruby):ArgumentError: (eval):87:in `show_complexity': bad value for range

### ISSUE THREAD

**Issue by rspeicher** [fousa/vim-flog#1]
Getting this error when I open a Ruby file. Here's my `mvim --version`

<pre>VIM - Vi IMproved 7.2 (2008 Aug 9, compiled Aug 21 2008 12:51:59)
MacOS X (unix) version
Compiled by Bjorn Winckler <bjorn.winckler@gmail.com>
Huge version with MacVim GUI.  Features included (+) or not (-):
+arabic +autocmd -balloon_eval +browse ++builtin_terms +byte_offset +cindent 
+clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info +comments 
+cryptv +cscope +cursorshape +dialog_con_gui +diff +digraphs +dnd -ebcdic 
+emacs_tags +eval +ex_extra +extra_search +farsi +file_in_path +find_in_path 
+float +folding -footer +fork() +fullscreen -gettext -hangul_input +iconv 
+insert_expand +jumplist +keymap +langmap +libcall +linebreak +lispindent 
+listcmds +localmap +menu +mksession +modify_fname +mouse +mouseshape 
+mouse_dec -mouse_gpm -mouse_jsbterm +mouse_netterm -mouse_sysmouse 
+mouse_xterm +multi_byte +multi_lang -mzscheme -netbeans_intg +odbeditor 
-osfiletype +path_extra -perl +postscript +printer +profile +python +quickfix 
+reltime +rightleft +ruby +scrollbind +signs +smartindent -sniff +statusline 
-sun_workshop +syntax +tag_binary +tag_old_static -tag_any_white -tcl +terminfo
 +termresponse +textobjects +title +toolbar +transparency +user_commands 
+vertsplit +virtualedit +visual +visualextra +viminfo +vreplace +wildignore 
+wildmenu +windows +writebackup -X11 -xfontset -xim -xsmp -xterm_clipboard 
-xterm_save 
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/Vim.app/Contents/Resources/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe -I. -Iproto -DMACOS_X_UNIX -no-cpp-precomp -I/Developer/SDKs/MacOSX10.4u.sdk/Developer/Headers/FlatCarbon  -g -O -isysroot /Developer/SDKs/MacOSX10.4u.sdk -arch i386 -arch ppc     -I/Developer/SDKs/MacOSX10.4u.sdk/System/Library/Frameworks/Python.framework/Versions/2.3/include/python2.3  -I/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin9.0 
Linking: gcc   -L. -arch ppc -arch i386  -L/usr/local/lib -isysroot /Developer/SDKs/MacOSX10.4u.sdk -arch i386 -arch ppc -o Vim -framework Cocoa -framework Carbon      -lncurses  -liconv    -framework Python  -lruby -lm   </pre>

I'm sure it's my fault, I'd just appreciate any ideas on how to fix it.

**Comment by fousa** [comment]
I'm on version 7.3, maybe you should try to upgrade...

[Here](https://github.com/b4winckler/macvim/wiki/Building) is a wiki on how to do this. I did it this way. Let me know if it works!

**Comment by rspeicher** [comment]
Installing 7.3 fixed it, so I'll close. Though you may want to update the README to say 7.3+

Thanks!

**Comment by fousa** [comment]
Ok! Great point!

Will do it later today!
